-- Delete the culinary_canvas database if it exists and recreate it
DROP DATABASE IF EXISTS culinary_canvas;
CREATE DATABASE culinary_canvas;

\c culinary_canvas

-- Create custom data types
CREATE TYPE recipe_time AS (hr INTEGER, min INTEGER);
CREATE TYPE units AS ENUM ('none', 'tsp', 'tbsp', 'cup', 'pinch', 'oz', 'ml', 'l', 'lbs', 'g', 'kg', 'slice');
CREATE TYPE ingredient AS (item VARCHAR(255), quantity DECIMAL, unit units);
CREATE TYPE tag AS ENUM ('Breakfast', 'Brunch', 'Lunch', 'Dinner', 'Snack', 'Dessert', 'Appetizer', 'Side Dish', 
'Easy', 'Quick', 'Simple', 'One-Pot', 'No-Bake', 'Beginner-Friendly', 'Healthy', 'Low-Carb', 'Low-Calorie', 'High Protein', 
'High Fiber', 'Vegan', 'Vegetarian', 'Gluten-Free', 'Dairy-Free', 'Keto', 'Paleo', 'High-Fiber', 'Sugar-Free', 'Low-Fat'
'Baked', 'Grilled', 'Roasted', 'Fried', 'Slow Cooker', 'Instant Pot', 'Air Fryer', 'Steamed', 'Toasted', 'Kid-Friendly', 'BBQ', 
'Comfort Food', 'Holiday', 'Italian', 'Mexican', 'Indian', 'Chinese', 'Japanese', 'Thai', 'Mediterranean', 'Middle Eastern', 
'American', 'French', 'Korean', 'Turkish', 'Spanish', 'Arab', 'Vietnamese', 'Greek', 'Hong Kong', 'Indonesian');
CREATE TYPE privacy_options AS ENUM ('public', 'private', 'custom');
CREATE TYPE custom_options AS (prof BOOLEAN, review BOOLEAN, fav BOOLEAN);
CREATE TYPE socials AS (facebook TEXT, youtube TEXT, tiktok TEXT, instagram TEXT);

-- Create the tables
CREATE TABLE users (
  uid INTEGER GENERATED BY DEFAULT AS IDENTITY,
  full_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) PRIMARY KEY UNIQUE NOT NULL,
  salt CHAR(16) NOT NULL,
  password_hash TEXT NOT NULL,
  profile_img BYTEA DEFAULT NULL,
  social socials DEFAULT (NULL, NULL, NULL, NULL),
  location TEXT DEFAULT '',
  privacy privacy_options DEFAULT 'public',
  custom_privacy custom_options DEFAULT (true, true, true),
  show_email BOOLEAN DEFAULT false
);

CREATE TABLE recipes (
  recid INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  recipe_name TEXT NOT NULL,
  author VARCHAR(255) NOT NULL,
  about TEXT DEFAULT '',
  img BYTEA DEFAULT NULL,
  prep_time recipe_time DEFAULT (0, 0),
  cook_time recipe_time DEFAULT (0, 0),
  tags tag ARRAY DEFAULT '{}',
  notes TEXT DEFAULT '',
  servings INTEGER DEFAULT 0,
  ingrs ingredient ARRAY DEFAULT '{}',
  steps TEXT ARRAY DEFAULT '{}',
  CONSTRAINT fk_recipe_author FOREIGN KEY (author) REFERENCES users(email) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE fav_recipes (
  user_email VARCHAR(255) NOT NULL,
  recid INTEGER NOT NULL,
  PRIMARY KEY (user_email, recid),
  CONSTRAINT fk_fav_user FOREIGN KEY (user_email) REFERENCES users(email) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_fav_recipe FOREIGN KEY (recid) REFERENCES recipes(recid) ON DELETE SET NULL
);

CREATE TABLE reviews (
  revid INTEGER GENERATED BY DEFAULT AS IDENTITY,
  author VARCHAR(255) NOT NULL,
  recipe INTEGER NOT NULL,
  created_at DATE DEFAULT CURRENT_DATE,
  comment TEXT DEFAULT '',
  rating DECIMAL DEFAULT 0,
  helpful INTEGER DEFAULT 0,
  PRIMARY KEY (author, recipe),
  CONSTRAINT fk_review_author FOREIGN KEY (author) REFERENCES users(email) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_review_recipe FOREIGN KEY (recipe) REFERENCES recipes(recid) ON DELETE SET NULL
);

-- Populate the tables
INSERT INTO users (full_name, email, salt, password_hash) VALUES
  ('John Smith', 'john@email.com', 'thisissalt', 'password123'), 
  ('Mary Sue', 'mary_sue@email.com', 'thisissalt', 'password123123'), 
  ('Larry Gary', 'notlarry@email.com', 'thisissalt', 'larrygary');

INSERT INTO recipes (recipe_name, author, about, prep_time, cook_time, tags, servings, ingrs, steps) VALUES
    ('Blueberry pancakes', 'mary_sue@email.com', 'This is my first recipe I made 15 years ago when I first started cooking. 
    These pancakes are fluffy and a masterpiece. Feel free to serve it with a cup of coffee for breakfast.', (0, 30), (0, 15), 
    ARRAY[('Breakfast')::tag, ('Easy')::tag, ('No-Bake')::tag, ('Beginner-Friendly')::tag], 1, ARRAY[
      ('All purpose flour', 2, 'cup')::ingredient,
      ('Blueberries', 0.5, 'cup')::ingredient,
      ('Baking powder', 1.5, 'tsp')::ingredient,
      ('Sugar', 2, 'tbsp')::ingredient,
      ('Milk', 1.25, 'cup')::ingredient,
      ('Butter, melted', 3, 'tbsp')::ingredient,
      ('Egg', 2, 'none')::ingredient
    ], ARRAY[
      'Mix flour, sugar, and baking powder in a bowl.',
      'Add milk, eggs, and butter; mix until smooth.',
      'Gently mix the blueberries into the mixture. Make sure not to overmix!',
      'Heat a lightly oiled griddle or frying pan over medium-high heat.',
      'Pour or scoop the batter onto the griddle, using approximately 1/4 cup for each pancake.',
      'Brown on both sides and serve hot.'
    ]),
    ('Avocado toasts', 'mary_sue@email.com', 'This is my go-to breakfast when I am busy and do not have time in the morning. 
    This recipe is very simple and easy and it contains ingredients that you probably have in your house. You can add whatever
    extra toppings you want on the toasts, like honey.', (0, 0), (0, 10), 
    ARRAY[('Breakfast')::tag, ('Easy')::tag, ('Quick')::tag, ('Healthy')::tag, ('Vegetarian')::tag, ('American')::tag, ('Toasted')::tag], 2, 
    ARRAY[
      ('Bread', 2, 'slice')::ingredient,
      ('Avocado', 1, 'none')::ingredient,
      ('Lemon juice', 1, 'tbsp')::ingredient,
      ('Salt', 1.25, 'tsp')::ingredient,
      ('Cottage cheese (optional)', 0.5, 'cup')::ingredient,
      ('Egg (optional)', 1, 'none')::ingredient,
      ('Cranberries (optional)', 0.25, 'cup')::ingredient
    ], ARRAY[
      'Put the 2 slices of any type of bread into the toaster. (I prefer sourdough bread.)',
      'While the bread is toasting, cut one large avocado (or 2 small avocados) and smash it on a bowl.',
      'Mix the lemon juice and salt in the smashed avocado.',
      'Evenly spread the avocado mixture onto the toasted bread.',
      'Finally, you can add whatever other toppings you want. I added cottage cheese and egg for extra protein. 
      I also added cranberries for some extra crunch'
    ]),
    ('Shrimp ramen', 'notlarry@email.com', 'This is a simple ramen recipe that contains minimum ingredients and satisfies your 
    craving for Japanese food.', (0, 10), (0, 30), 
    ARRAY[('Lunch')::tag, ('Dinner')::tag, ('Simple')::tag, ('Beginner-Friendly')::tag, ('One-Pot')::tag, ('Japanese')::tag], 2, ARRAY[
      ('Instant ramen noodles', 300, 'g')::ingredient,
      ('Shrimps, peeled', 150, 'g')::ingredient,
      ('Green onion', 2, 'none')::ingredient,
      ('Carrot', 1, 'none')::ingredient,
      ('Ginger, grated', 3, 'tsp')::ingredient,
      ('Garlic, grated', 4, 'tsp')::ingredient,
      ('Broth, chicken or vegetable', 2, 'cup')::ingredient,
      ('Water', 2, 'cup')::ingredient, 
      ('Sesame oil', 1, 'tbsp')::ingredient
    ], ARRAY[
      'Shred the carrot into thin strips. Cut the green onions into small pieces and make sure to separate the white and green parts 
      of the green onions. Mince the ginger and garlic.',
      'In a wok, fry the sesame oil, white part of the green onions, ginger, and garlic in medium-low heat until fragrant.', 
      'Add the shrimps to the wok and fry it until the shrimp turns pink.', 
      'Add the broth and water. Bring it to a simmer for 5 minutes.',
      'Add the instant noodles to the liquid and simmer for another 5 minutes or until the noodles softened.', 
      'Remove from heat and stir in the carrots and the rest of the green onions for garnish. Add sesame oil, soy sauce, and salt to taste.'
    ]);

INSERT INTO fav_recipes (user_email, recid) VALUES 
  ('john@email.com', 1),
  ('john@email.com', 3),
  ('mary_sue@email.com', 3),
  ('notlarry@email.com', 1),
  ('notlarry@email.com', 2);

INSERT INTO reviews (author, recipe, comment, rating) VALUES 
  ('john@email.com', 1, 'This is the best pancake recipe I''ve ever tried. It''s so easy and quick to make. I love it!', 5),
  ('john@email.com', 3, 'I love Japanese food, especially ramen, so this recipe is perfect for me.', 4),
  ('notlarry@email.com', 1, 'As Mary said, the pancakes are fluffy and it is an easy recipe to follow. But I prefer putting chocolate
  chips on my pancake rather than blueberries...', 3);
